services:
  postgres:
    image: postgres:16
    container_name: ethnograph-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ethnograph
      POSTGRES_USER: ethnograph_user
      POSTGRES_PASSWORD: ethnograph_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/sql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
